# Oklahoma application figures and LaTeX table fragments for the paper.
#
# Usage (from repo root):
#   Rscript inst/oklahoma/paper/oklahoma_paper_assets.R
#   Rscript inst/oklahoma/paper/oklahoma_paper_assets.R --input output/oklahoma/oklahoma_results_job5226010.rds
#
# Or in R: setwd("<repo>"); source("inst/oklahoma/paper/oklahoma_paper_assets.R")
#
# Writes:
#   plots/oklahoma/*.pdf          — figures referenced by oklahoma_application_section.tex
#   inst/oklahoma/paper/generated/*.tex — \input-able tables (booktabs), including tab_ok_sem_config.tex

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(data.table)
})

find_repo_root <- function(start_dir = getwd()) {
  cur <- normalizePath(start_dir, winslash = "/", mustWork = TRUE)
  repeat {
    if (dir.exists(file.path(cur, ".git"))) return(cur)
    parent <- dirname(cur)
    if (identical(parent, cur)) return(normalizePath(start_dir, winslash = "/", mustWork = TRUE))
    cur <- parent
  }
}

get_arg_val <- function(args, flag, default = NULL) {
  idx <- which(args == flag)
  if (length(idx) < 1L || idx[[1]] >= length(args)) return(default)
  args[[idx[[1]] + 1L]]
}

args <- commandArgs(trailingOnly = TRUE)
repo_root <- find_repo_root()
input_rds <- normalizePath(
  get_arg_val(args, "--input", file.path(repo_root, "output", "oklahoma", "oklahoma_results_job5226010.rds")),
  winslash = "/",
  mustWork = TRUE
)
plots_dir <- normalizePath(
  get_arg_val(args, "--plots-dir", file.path(repo_root, "plots", "oklahoma")),
  winslash = "/",
  mustWork = FALSE
)
tex_dir <- normalizePath(
  get_arg_val(args, "--tex-dir", file.path(repo_root, "inst", "oklahoma", "paper", "generated")),
  winslash = "/",
  mustWork = FALSE
)
data_dir <- normalizePath(
  get_arg_val(
    args,
    "--data-dir",
    file.path(repo_root, "inst", "oklahoma", "oklahoma_induced_seismicity_data_regional20150318")
  ),
  winslash = "/",
  mustWork = FALSE
)

dir.create(plots_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(tex_dir, recursive = TRUE, showWarnings = FALSE)

if (!file.exists(input_rds)) stop("Input RDS not found: ", input_rds)

res <- readRDS(input_rds)
if (is.null(res$fits_named$E) || is.null(res$fits_named$F)) {
  stop("RDS must contain fits_named$E and fits_named$F.")
}

boot_obj <- res$bootstrap_ate
if (is.null(boot_obj) || is.null(boot_obj$fit_E$replicate_summary) || is.null(boot_obj$fit_F$replicate_summary)) {
  stop("Bootstrap replicate summaries required (bootstrap_ate$fit_E / fit_F$replicate_summary).")
}

ate_days <- suppressWarnings(as.numeric(res$config$ATE_WINDOW_DAYS))
if (!is.finite(ate_days)) ate_days <- 100

fit_E <- res$fits_named$E
fit_F <- res$fits_named$F

# ---- Expected-count rows (same quantities as HTML report / former Rmd appendix) ----
extract_totals <- function(ate_obj) {
  out <- list(c_total = numeric(0), t_total = numeric(0), saved_total = numeric(0))
  if (is.null(ate_obj) || is.null(ate_obj$all_nothing_sim)) return(out)
  sim_df <- as.data.frame(ate_obj$all_nothing_sim)
  if ("c_total" %in% names(sim_df)) out$c_total <- suppressWarnings(as.numeric(sim_df$c_total))
  if ("t_total" %in% names(sim_df)) out$t_total <- suppressWarnings(as.numeric(sim_df$t_total))
  if ("total_saved" %in% names(sim_df)) out$saved_total <- suppressWarnings(as.numeric(sim_df$total_saved))
  if (length(out$saved_total) < 1L && length(out$c_total) > 0 && length(out$t_total) > 0) {
    out$saved_total <- out$c_total - out$t_total
  }
  out
}

summ_one <- function(fit_obj) {
  tt <- extract_totals(if (!is.null(fit_obj)) fit_obj$ate else NULL)
  c_mean <- if (length(tt$c_total) > 0) mean(tt$c_total, na.rm = TRUE) else NA_real_
  t_mean <- if (length(tt$t_total) > 0) mean(tt$t_total, na.rm = TRUE) else NA_real_
  saved_mean <- if (length(tt$saved_total) > 0) mean(tt$saved_total, na.rm = TRUE) else NA_real_
  c(round(c_mean, 0), round(t_mean, 0), round(saved_mean, 0))
}

vals_E <- summ_one(fit_E)
vals_F <- summ_one(fit_F)

write_tex_ok_counts <- function(path) {
  fmt <- function(x) if (is.finite(x)) as.character(as.integer(x)) else "---"
  lines <- c(
    "% Auto-generated by oklahoma_paper_assets.R — do not edit by hand",
    "\\begin{table}",
    "\\caption{\\label{tab:ok_counts}Observed and model-implied all-or-nothing expected counts naive and SEM approach.}",
    "\\centering",
    "\\begin{tabular}[t]{lrrr}",
    "\\toprule",
    "Method & $E[N_C]$ & $E[N_A]$ & $\\Delta=E[N_C]-E[N_A]$\\\\",
    "\\midrule",
    sprintf("Naive & %s & %s & %s\\\\", fmt(vals_E[1]), fmt(vals_E[2]), fmt(vals_E[3])),
    sprintf("SEM & %s & %s & %s\\\\", fmt(vals_F[1]), fmt(vals_F[2]), fmt(vals_F[3])),
    "\\bottomrule",
    "\\end{tabular}",
    "\\end{table}"
  )
  writeLines(lines, path)
  message("Wrote ", path)
}

# ---- Bootstrap (bias-corrected replicates, same as oklahoma_publication_ef.R) ----
boot_E <- as.data.frame(boot_obj$fit_E$replicate_summary)
boot_F <- as.data.frame(boot_obj$fit_F$replicate_summary)
boot_E$model <- "Naive Bivaraite ETAS with KDE"
boot_F$model <- "SEM Bivariate ETAS with KDE"
boot_df <- bind_rows(boot_E, boot_F)

if (!"ate_total_mean" %in% names(boot_df)) {
  stop("Expected bootstrap column ate_total_mean is missing.")
}
boot_df <- boot_df %>% filter(is.finite(.data$ate_total_mean))

get_total_effect_sim <- function(ate_obj) {
  if (is.null(ate_obj) || is.null(ate_obj$all_nothing_sim)) return(numeric(0))
  sim_df <- as.data.frame(ate_obj$all_nothing_sim)
  if ("total_saved" %in% names(sim_df)) return(suppressWarnings(as.numeric(sim_df$total_saved)))
  if ("total_effect" %in% names(sim_df)) return(suppressWarnings(as.numeric(sim_df$total_effect)))
  numeric(0)
}
obs_ate_mean <- function(fit_obj) {
  if (is.null(fit_obj) || is.null(fit_obj$ate)) return(NA_real_)
  vals <- get_total_effect_sim(fit_obj$ate)
  vals <- vals[is.finite(vals)]
  if (length(vals) < 1L) return(NA_real_)
  mean(vals, na.rm = TRUE)
}
recenter_boot <- function(boot_vals, target_mean) {
  bv <- suppressWarnings(as.numeric(boot_vals))
  if (!is.finite(target_mean) || is.na(target_mean)) return(bv)
  bmean <- mean(bv, na.rm = TRUE)
  if (!is.finite(bmean) || is.na(bmean)) return(bv)
  bv + (target_mean - bmean)
}

obs_E <- obs_ate_mean(fit_E)
obs_F <- obs_ate_mean(fit_F)
target_mean_by_model <- c(
  "Naive Bivaraite ETAS with KDE" = obs_E,
  "SEM Bivariate ETAS with KDE" = obs_F
)
boot_df <- boot_df %>%
  group_by(.data$model) %>%
  mutate(ate_total_mean = recenter_boot(.data$ate_total_mean, target_mean_by_model[.data$model[[1]]])) %>%
  ungroup() %>%
  filter(is.finite(.data$ate_total_mean))

boot_df <- boot_df %>%
  group_by(.data$model) %>%
  arrange(.data$rep, .by_group = TRUE) %>%
  mutate(
    rep_idx = row_number(),
    running_mean = cumsum(.data$ate_total_mean) / row_number()
  ) %>%
  ungroup()

sim_E <- as.data.frame(fit_E$ate$all_nothing_sim)
sim_F <- as.data.frame(fit_F$ate$all_nothing_sim)
sim_E$model <- "Naive Bivaraite ETAS with KDE"
sim_F$model <- "SEM Bivariate ETAS with KDE"
sim_df <- bind_rows(sim_E, sim_F) %>% filter(is.finite(.data$total_saved))

theme_pub <- theme_minimal(base_size = 13) +
  theme(
    legend.position = "top",
    plot.title = element_blank(),
    strip.text = element_text(face = "bold")
  )

p_boot_hist <- ggplot(boot_df, aes(x = .data$ate_total_mean, fill = .data$model)) +
  geom_histogram(bins = 30, alpha = 0.55, position = "identity") +
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.9) +
  scale_fill_manual(values = c(
    "Naive Bivaraite ETAS with KDE" = "#e6550d",
    "SEM Bivariate ETAS with KDE" = "#3182bd"
  )) +
  labs(
    x = bquote(hat(Delta)[AoN] ~ "(bias-corrected bootstrap replicate mean total saved /" ~ .(ate_days) ~ " days)"),
    y = "Count",
    fill = "Model"
  ) +
  xlim(-500, 700) +
  theme_pub

p_boot_ecdf <- ggplot(boot_df, aes(x = .data$ate_total_mean, colour = .data$model)) +
  stat_ecdf(linewidth = 1.0) +
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.9) +
  scale_colour_manual(values = c(
    "Naive Bivaraite ETAS with KDE" = "#e6550d",
    "SEM Bivariate ETAS with KDE" = "#3182bd"
  )) +
  labs(
    x = bquote(hat(Delta)[AoN] ~ "(bias-corrected bootstrap replicate mean total saved /" ~ .(ate_days) ~ " days)"),
    y = "Cumulative proportion",
    colour = "Model"
  ) +
  theme_pub

p_boot_running <- ggplot(boot_df, aes(x = .data$rep_idx, y = .data$running_mean, colour = .data$model)) +
  geom_line(linewidth = 0.9) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.9) +
  facet_wrap(~model, scales = "free_y") +
  scale_colour_manual(values = c(
    "Naive Bivaraite ETAS with KDE" = "#e6550d",
    "SEM Bivariate ETAS with KDE" = "#3182bd"
  )) +
  labs(
    x = "Bootstrap replicate index",
    y = bquote("Running mean of " ~ hat(Delta)[AoN]),
    colour = "Model"
  ) +
  theme_pub +
  theme(legend.position = "none")

p_sim_hist <- ggplot(sim_df, aes(x = .data$total_saved, fill = .data$model)) +
  geom_histogram(bins = 30, alpha = 0.55, position = "identity") +
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.9) +
  scale_fill_manual(values = c(
    "Naive Bivaraite ETAS with KDE" = "#e6550d",
    "SEM Bivariate ETAS with KDE" = "#3182bd"
  )) +
  labs(
    x = bquote(hat(Delta)[AoN] ~ "(Monte Carlo total saved /" ~ .(ate_days) ~ " days)"),
    y = "Count",
    fill = "Model"
  ) +
  theme_pub

# Paper-facing names (match oklahoma_application_section.tex)
ggsave(file.path(plots_dir, "ATE_diff.pdf"), p_boot_hist, width = 8.8, height = 5.2)
ggsave(file.path(plots_dir, "ok_bootstrap_ecdf.pdf"), p_boot_ecdf, width = 8.8, height = 5.2)
ggsave(file.path(plots_dir, "ok_bootstrap_running_mean.pdf"), p_boot_running, width = 8.8, height = 5.2)
ggsave(file.path(plots_dir, "ok_sim_total_saved_hist.pdf"), p_sim_hist, width = 8.8, height = 5.2)
message("Wrote figures under ", plots_dir)

# Cumulative catalog plot
ev_csv <- file.path(data_dir, "events_all.csv")
if (file.exists(ev_csv) && requireNamespace("jsonlite", quietly = TRUE)) {
  meta_ok <- jsonlite::fromJSON(file.path(data_dir, "metadata.json"), simplifyVector = TRUE)
  m0_c <- res$config$ETAS_M0
  if (is.null(m0_c) || !length(m0_c) || all(is.na(m0_c))) m0_c <- meta_ok$design$min_mag
  ev_all <- fread(ev_csv)
  ev_all[, time_utc := as.POSIXct(time_utc, tz = "UTC")]
  t_star_utc <- as.POSIXct(meta_ok$design$t_star_utc, tz = "UTC")
  ev_all[, t_days := as.numeric(difftime(time_utc, t_star_utc, units = "days"))]
  setorder(ev_all, time_utc)
  ev_all <- ev_all[mag >= m0_c]
  ev_all[, cum_n := seq_len(.N)]
  t_star_lbl <- format(t_star_utc, "%d %b %Y", tz = "UTC")
  p_cum <- ggplot(ev_all, aes(x = .data$t_days, y = .data$cum_n)) +
    geom_step(color = "#2171b5", linewidth = 0.6) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "red", linewidth = 0.8) +
    annotate(
      "text",
      x = 5,
      y = max(ev_all$cum_n, na.rm = TRUE) * 0.1,
      label = paste0("OCC directive\n(", t_star_lbl, ")"),
      color = "red",
      hjust = 0,
      size = 3.5
    ) +
    labs(x = "Days since treatment (t*)", y = "Cumulative events") +
    theme_minimal(base_size = 13)
  ggsave(file.path(plots_dir, "cumulative_count.pdf"), p_cum, width = 8.8, height = 5.2)
  message("Wrote cumulative_count.pdf")
} else {
  message(
    "Skipped cumulative_count.pdf (need ", ev_csv,
    " and package jsonlite)."
  )
}

tex_escape_cfg <- function(s) {
  s <- as.character(s)
  # Avoid gsub(replacement=...) backslash rules: insert explicit UTF-8 bytes for LaTeX escapes.
  s <- gsub("&", intToUtf8(c(92L, 38L)), s, fixed = TRUE)
  s <- gsub("%", intToUtf8(c(92L, 37L)), s, fixed = TRUE)
  s <- gsub("_", intToUtf8(c(92L, 95L)), s, fixed = TRUE)
  s <- gsub("#", intToUtf8(c(92L, 35L)), s, fixed = TRUE)
  s
}

fmt_cfg_val <- function(x, default = "---") {
  if (is.null(x) || length(x) < 1L) return(default)
  v <- x[[1L]]
  if (is.logical(v)) return(if (isTRUE(v)) "yes" else if (identical(v, FALSE)) "no" else default)
  if (is.numeric(v)) {
    if (!is.finite(v)) return(default)
    if (abs(v - round(v)) < 1e-9) return(as.character(as.integer(round(v))))
    return(as.character(signif(v, 6)))
  }
  if (is.character(v) && !nzchar(v)) return(default)
  tex_escape_cfg(as.character(v)[1])
}

write_tex_ok_sem_config <- function(cfg, path, rds_basename) {
  if (is.null(cfg) || length(cfg) < 1L) {
    cfg <- list()
  }
  pilot_cores <- cfg$SEM_PILOT_CORES
  pc1 <- if (is.null(pilot_cores) || length(pilot_cores) < 1L) {
    NA_integer_
  } else if (is.list(pilot_cores)) {
    suppressWarnings(as.integer(pilot_cores[[1L]]))
  } else {
    suppressWarnings(as.integer(pilot_cores[[1L]]))
  }
  pilot_cores_txt <- if (length(pc1) < 1L || is.na(pc1)) "auto" else as.character(pc1)

  rows <- rbind(
    c("SEM outer rounds ($N_{\\mathrm{iter}}$)", fmt_cfg_val(cfg$SEM_N_ITER)),
    c("Inner iterations (per outer round)", fmt_cfg_val(cfg$SEM_INNER_ITER)),
    c("Inner proposals (per inner iteration)", fmt_cfg_val(cfg$SEM_INNER_PROPS)),
    c("Retained labellings (per outer round)", fmt_cfg_val(cfg$SEM_N_LABELLINGS)),
    c("Outer optim cap (adaptive SEM, uni.~path)", fmt_cfg_val(cfg$SEM_OUTER_MAXIT)),
    c("Outer optim cap (bivariate ETAS path)", fmt_cfg_val(cfg$SEM_OUTER_MAXIT_BIV)),
    c("Warm-start fixed full-parameter step", fmt_cfg_val(cfg$SEM_WARMSTART_FIXED)),
    c("Relabelling selection method", fmt_cfg_val(cfg$SEM_OPTIM_METHOD)),
    c("Relabelling selection temperature", fmt_cfg_val(cfg$SEM_SELECTION_TEMPERATURE)),
    c("Proposal change factor", fmt_cfg_val(cfg$SEM_CHANGE_FACTOR)),
    c("Change-factor min.~multiplier", fmt_cfg_val(cfg$SEM_CHANGE_FACTOR_MIN_MULT)),
    c("Change-factor max.~multiplier", fmt_cfg_val(cfg$SEM_CHANGE_FACTOR_MAX_MULT)),
    c("Max.~relabel step (fraction of points)", fmt_cfg_val(cfg$SEM_MAX_RELABEL_STEP_FRAC)),
    c("Forced param.~update flip fraction", fmt_cfg_val(cfg$SEM_FORCE_PARAM_UPDATE_FLIP_FRAC)),
    c("Temporal relabel weight", fmt_cfg_val(cfg$SEM_TEMPORAL_WEIGHT)),
    c("Temporal relabel scale (days)", fmt_cfg_val(cfg$SEM_TEMPORAL_SCALE_DAYS)),
    c("Pilot tuning enabled", fmt_cfg_val(cfg$RUN_SEM_PILOT)),
    c("Pilot inner iterations", fmt_cfg_val(cfg$SEM_PILOT_INNER_ITER)),
    c("Pilot cores", pilot_cores_txt),
    c("Pilot max.~combinations", fmt_cfg_val(cfg$SEM_PILOT_MAX_COMBOS))
  )

  lines <- c(
    "% Auto-generated by oklahoma_paper_assets.R — do not edit by hand",
    "\\begin{table}[t]",
    "\\centering",
    "\\small",
    sprintf(
      "\\caption{\\label{tab:ok_sem_config}Stochastic SEM configuration for the Oklahoma \\emph{SEM KDE fit}. Values are taken from the archived run \\texttt{%s}.}",
      tex_escape_cfg(rds_basename)
    ),
    "\\begin{tabular}{@{}l@{\\quad}l@{}}",
    "\\toprule",
    "Setting & Value\\\\",
    "\\midrule"
  )
  for (i in seq_len(nrow(rows))) {
    lines <- c(lines, sprintf("%s & %s\\\\", rows[i, 1], rows[i, 2]))
  }
  lines <- c(
    lines,
    "\\bottomrule",
    "\\end{tabular}",
    "\\end{table}"
  )
  writeLines(lines, path)
  message("Wrote ", path)
}

# ---- LaTeX fragments ----
write_tex_ok_counts(file.path(tex_dir, "tab_ok_counts.tex"))
write_tex_ok_sem_config(
  res$config,
  file.path(tex_dir, "tab_ok_sem_config.tex"),
  basename(input_rds)
)

summ <- boot_df %>%
  group_by(.data$model) %>%
  summarize(
    n_boot = n(),
    mean_saved = mean(.data$ate_total_mean, na.rm = TRUE),
    sd_saved = sd(.data$ate_total_mean, na.rm = TRUE),
    q025 = as.numeric(quantile(.data$ate_total_mean, 0.025, na.rm = TRUE)),
    q50 = as.numeric(quantile(.data$ate_total_mean, 0.50, na.rm = TRUE)),
    q975 = as.numeric(quantile(.data$ate_total_mean, 0.975, na.rm = TRUE)),
    .groups = "drop"
  )

lines_boot <- c(
  "% Auto-generated by oklahoma_paper_assets.R",
  "\\begin{table}",
  "\\caption{\\label{tab:ok_bootstrap_summary}Bootstrap summary (bias-corrected replicate means of $\\hat\\Delta_{\\mathrm{AoN}}$, days matching analysis window).}",
  "\\centering",
  "\\begin{tabular}[t]{@{}lrrrrrr@{}}",
  "\\toprule",
  "Model & $n$ & Mean & SD & 2.5\\% & 50\\% & 97.5\\%\\\\",
  "\\midrule"
)
fmt1 <- function(x) sprintf("%.1f", as.numeric(x))
for (i in seq_len(nrow(summ))) {
  lab <- if (grepl("Naive", summ$model[i])) "Naive" else "SEM"
  lines_boot <- c(
    lines_boot,
    sprintf(
      "%s & %d & %s & %s & %s & %s & %s\\\\",
      lab,
      as.integer(summ$n_boot[i]),
      fmt1(summ$mean_saved[i]),
      fmt1(summ$sd_saved[i]),
      fmt1(summ$q025[i]),
      fmt1(summ$q50[i]),
      fmt1(summ$q975[i])
    )
  )
}
lines_boot <- c(
  lines_boot,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}"
)
writeLines(lines_boot, file.path(tex_dir, "tab_ok_bootstrap_summary.tex"))
message("Wrote ", file.path(tex_dir, "tab_ok_bootstrap_summary.tex"))

utils::write.csv(summ, file.path(tex_dir, "ef_bootstrap_summary.csv"), row.names = FALSE)

meta_out <- list(
  input_rds = input_rds,
  ate_days = ate_days,
  plots_dir = plots_dir,
  tex_dir = tex_dir,
  generated = c(
    "plots/oklahoma/ATE_diff.pdf",
    "plots/oklahoma/ok_bootstrap_ecdf.pdf",
    "plots/oklahoma/ok_bootstrap_running_mean.pdf",
    "plots/oklahoma/ok_sim_total_saved_hist.pdf",
    "plots/oklahoma/cumulative_count.pdf",
    "inst/oklahoma/paper/generated/tab_ok_counts.tex",
    "inst/oklahoma/paper/generated/tab_ok_sem_config.tex",
    "inst/oklahoma/paper/generated/tab_ok_bootstrap_summary.tex"
  )
)
saveRDS(meta_out, file.path(tex_dir, "build_manifest.rds"))
message("Done. Manifest: ", file.path(tex_dir, "build_manifest.rds"))
