// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hawkes_loglik_inhom_cpp
double hawkes_loglik_inhom_cpp(NumericVector t, NumericVector x, NumericVector y, NumericVector W_val, double mu, double alpha, double beta, double K, double areaS, double t_max);
RcppExport SEXP _PPDisentangle_hawkes_loglik_inhom_cpp(SEXP tSEXP, SEXP xSEXP, SEXP ySEXP, SEXP W_valSEXP, SEXP muSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP KSEXP, SEXP areaSSEXP, SEXP t_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W_val(W_valSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type areaS(areaSSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(hawkes_loglik_inhom_cpp(t, x, y, W_val, mu, alpha, beta, K, areaS, t_max));
    return rcpp_result_gen;
END_RCPP
}
// sim_hawkes_children_cpp
DataFrame sim_hawkes_children_cpp(NumericVector parent_x, NumericVector parent_y, NumericVector parent_t, double alpha, double beta, double K, double t_min, double t_max, double x_min, double x_max, double y_min, double y_max);
RcppExport SEXP _PPDisentangle_sim_hawkes_children_cpp(SEXP parent_xSEXP, SEXP parent_ySEXP, SEXP parent_tSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP KSEXP, SEXP t_minSEXP, SEXP t_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP y_minSEXP, SEXP y_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type parent_x(parent_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parent_y(parent_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parent_t(parent_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type t_min(t_minSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< double >::type y_min(y_minSEXP);
    Rcpp::traits::input_parameter< double >::type y_max(y_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_hawkes_children_cpp(parent_x, parent_y, parent_t, alpha, beta, K, t_min, t_max, x_min, x_max, y_min, y_max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PPDisentangle_hawkes_loglik_inhom_cpp", (DL_FUNC) &_PPDisentangle_hawkes_loglik_inhom_cpp, 10},
    {"_PPDisentangle_sim_hawkes_children_cpp", (DL_FUNC) &_PPDisentangle_sim_hawkes_children_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_PPDisentangle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
