# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Batched bivariate ETAS log-likelihood over labellings
#'
#' @param t Event times (shared across labellings, window starts at 0).
#' @param x,y Spatial coordinates (shared).
#' @param mag Event magnitudes (shared).
#' @param process_ids Integer matrix n x K: 0 = control, 1 = treated.
#' @param W0s,W1s Numeric matrices n x K of background weights.
#' @param mu_0,mu_1 Background rates.
#' @param A_00,alpha_m_00,A_11,alpha_m_11,A_01,alpha_m_01,A_10,alpha_m_10
#'   Productivity parameters.
#' @param cc,p,D,gamma_par,q Shared structural parameters.
#' @param m0 Reference magnitude.
#' @param areaS_0,areaS_1 Active areas.
#' @param t_max Observation window length.
#' @param t_trunc Temporal truncation (negative to disable).
#' @param bg_exposure_0,bg_exposure_1 Time span over which each background is
#'   switched on (compensator charge). Negative (default) means the full
#'   window \code{t_max}.
#' @param n_threads Number of worker threads (1 = serial).
#' @return Length-K numeric vector of log-likelihoods.
#' @keywords internal
etas_bivariate_loglik_batch_cpp <- function(t, x, y, mag, process_ids, W0s, W1s, mu_0, mu_1, A_00, alpha_m_00, A_11, alpha_m_11, A_01, alpha_m_01, A_10, alpha_m_10, cc, p, D, gamma_par, q, m0, areaS_0, areaS_1, t_max, t_trunc = -1.0, bg_exposure_0 = -1.0, bg_exposure_1 = -1.0, n_threads = 1L) {
    .Call(`_PPDisentangle_etas_bivariate_loglik_batch_cpp`, t, x, y, mag, process_ids, W0s, W1s, mu_0, mu_1, A_00, alpha_m_00, A_11, alpha_m_11, A_01, alpha_m_01, A_10, alpha_m_10, cc, p, D, gamma_par, q, m0, areaS_0, areaS_1, t_max, t_trunc, bg_exposure_0, bg_exposure_1, n_threads)
}

#' Bivariate ETAS log-likelihood with cross-excitation
#'
#' Computes the joint log-likelihood of a two-component ETAS model where
#' events in each process can trigger offspring in both processes via a
#' 2x2 kernel matrix.
#'
#' The conditional intensity for process k in {0, 1} is:
#' \deqn{\lambda_k(t,x,y) = \frac{\mu_k}{|S_k|} W_k(x,y) +
#'   \sum_{l \in \{0,1\}} \sum_{t_j < t,\, \mathrm{proc}_j = l}
#'     A_{kl}\,e^{\alpha_{kl}(m_j - m_0)}\,g(\Delta t)\,f(\Delta x, \Delta y | m_j)}
#'
#' The four kernel components (child, parent) are:
#'   - (0,0): control self-excitation
#'   - (0,1): treated events exciting control intensity
#'   - (1,0): control events exciting treated intensity
#'   - (1,1): treated self-excitation
#'
#' Temporal and spatial kernels g, f use shared structural parameters
#' (c, p, D, gamma, q), identical to the univariate ETAS formulation.
#'
#' The pairwise product of power-law kernels is evaluated as a single fused
#' exponential, exp(-p*log(1+dt/c) - q*log(1+r2/d)), and all per-parent
#' constants are hoisted out of the inner pair loop. This is mathematically
#' identical to evaluating the two pow() factors separately (results agree
#' to floating-point rounding).
#'
#' @param t          Event times (sorted ascending, window starts at 0).
#' @param x,y        Spatial coordinates.
#' @param mag        Event magnitudes.
#' @param process_id Integer vector: 0 = control, 1 = treated.
#' @param W_val_0    Background weights for control process (0 in treated region).
#' @param W_val_1    Background weights for treated process (0 in control region).
#' @param mu_0,mu_1  Background rates for control and treated.
#' @param A_00,alpha_m_00  Control self-excitation productivity.
#' @param A_11,alpha_m_11  Treated self-excitation productivity.
#' @param A_01,alpha_m_01  Treated-to-control cross-excitation.
#' @param A_10,alpha_m_10  Control-to-treated cross-excitation.
#' @param cc,p,D,gamma_par,q  Shared structural parameters.
#' @param m0         Reference magnitude.
#' @param areaS_0    Active area for control background.
#' @param areaS_1    Active area for treated background.
#' @param t_max      Length of temporal observation window.
#' @param t_trunc    Temporal truncation (negative to disable).
#' @param bg_exposure_0,bg_exposure_1 Time span over which each background is
#'   switched on (compensator charge). Negative (default) means the full
#'   window \code{t_max}. Use these when a policy mask zeroes a background
#'   for part of the window (e.g. treated background only after treatment).
#' @return Scalar joint log-likelihood.
etas_bivariate_loglik_cpp <- function(t, x, y, mag, process_id, W_val_0, W_val_1, mu_0, mu_1, A_00, alpha_m_00, A_11, alpha_m_11, A_01, alpha_m_01, A_10, alpha_m_10, cc, p, D, gamma_par, q, m0, areaS_0, areaS_1, t_max, t_trunc = -1.0, bg_exposure_0 = -1.0, bg_exposure_1 = -1.0) {
    .Call(`_PPDisentangle_etas_bivariate_loglik_cpp`, t, x, y, mag, process_id, W_val_0, W_val_1, mu_0, mu_1, A_00, alpha_m_00, A_11, alpha_m_11, A_01, alpha_m_01, A_10, alpha_m_10, cc, p, D, gamma_par, q, m0, areaS_0, areaS_1, t_max, t_trunc, bg_exposure_0, bg_exposure_1)
}

#' Simulate bivariate ETAS offspring via BFS branching
#'
#' Each parent in process k generates offspring in BOTH processes via
#' the 2x2 kernel matrix.  Offspring counts are:
#'   n_{k->l} ~ Poisson(A_{lk} * exp(alpha_m_{lk} * (m - m0)))
#' for each child process l in {0, 1}.
#'
#' Temporal delays, spatial displacements, and magnitude assignment
#' are identical to the univariate ETAS simulation (shared structural
#' parameters c, p, D, gamma, q).
#'
#' @param parent_x,parent_y,parent_t,parent_mag  Parent coordinates.
#' @param parent_process  Integer vector: 0 = control, 1 = treated.
#' @param A_00,alpha_m_00  Control self-excitation.
#' @param A_11,alpha_m_11  Treated self-excitation.
#' @param A_01,alpha_m_01  Treated-to-control cross-excitation.
#' @param A_10,alpha_m_10  Control-to-treated cross-excitation.
#' @param cc,p,D,gamma_par,q  Shared structural parameters.
#' @param m0         Reference magnitude.
#' @param beta_gr    Gutenberg-Richter beta (negative to use mag_pool).
#' @param t_min,t_max  Temporal window.
#' @param x_min,x_max,y_min,y_max  Spatial bounding box.
#' @param t_trunc    Temporal truncation (negative to disable).
#' @param mag_pool   Magnitude pool for resampling.
#' @param max_generations Maximum offspring generations to simulate. Negative
#'   values retain the full branching process; one returns immediate children.
#' @return List with x, y, t, mag, process_id of all offspring.
sim_etas_bivariate_children_cpp <- function(parent_x, parent_y, parent_t, parent_mag, parent_process, A_00, alpha_m_00, A_11, alpha_m_11, A_01, alpha_m_01, A_10, alpha_m_10, cc, p, D, gamma_par, q, m0, beta_gr, t_min, t_max, x_min, x_max, y_min, y_max, t_trunc = -1.0, mag_pool = as.numeric( c()), max_generations = -1L) {
    .Call(`_PPDisentangle_sim_etas_bivariate_children_cpp`, parent_x, parent_y, parent_t, parent_mag, parent_process, A_00, alpha_m_00, A_11, alpha_m_11, A_01, alpha_m_01, A_10, alpha_m_10, cc, p, D, gamma_par, q, m0, beta_gr, t_min, t_max, x_min, x_max, y_min, y_max, t_trunc, mag_pool, max_generations)
}

#' ETAS log-likelihood for an inhomogeneous spatio-temporal point process
#'
#' Computes the log-likelihood of an Epidemic-Type Aftershock Sequence (ETAS)
#' model on a marked spatio-temporal point pattern.
#'
#' **Conditional intensity:**
#' \deqn{\lambda(t,x,y) = \frac{\mu}{|S|} W(x,y) +
#'   \sum_{t_j < t} \kappa(m_j)\, g(t - t_j)\, f(x - x_j, y - y_j \mid m_j)}
#'
#' **Productivity:**
#' \deqn{\kappa(m) = A \exp\bigl(\alpha_m (m - m_0)\bigr)}
#'
#' **Omori-Utsu temporal kernel (normalised density on \eqn{[0,\infty)}
#' when \eqn{p > 1}):**
#' \deqn{g(\Delta t) = \frac{p - 1}{c}\Bigl(1 + \frac{\Delta t}{c}\Bigr)^{-p}}
#'
#' **Isotropic power-law spatial kernel (Zhuang et al. 2002):**
#' \deqn{f(x,y \mid m) = \frac{q - 1}{\pi\, d(m)}
#'   \Bigl(1 + \frac{r^2}{d(m)}\Bigr)^{-q}, \quad r^2 = x^2 + y^2}
#' with \eqn{d(m) = D \exp\bigl(\gamma (m - m_0)\bigr)}.
#'
#' **Compensator (integral of intensity):**
#' \deqn{\int_0^T \lambda\,\mathrm{d}t \approx \mu T +
#'   \sum_i \kappa(m_i)\bigl[1 - \bigl(1 + h_i / c\bigr)^{-(p-1)}\bigr]}
#' where \eqn{h_i = \min(T - t_i,\; t_{\mathrm{trunc}})} when temporal
#' truncation is active and \eqn{h_i = T - t_i} otherwise.  The spatial
#' kernel integrates to 1 over \eqn{\mathbb{R}^2} (infinite-plane
#' approximation, consistent with the Hawkes implementation).
#'
#' When truncation is active the temporal density is renormalised so that
#' it integrates to 1 over \eqn{[0, t_{\mathrm{trunc}}]}:
#' \deqn{G(t_{\mathrm{trunc}}) = 1 - (1 + t_{\mathrm{trunc}}/c)^{-(p-1)}}
#'
#' The pairwise product of power-law kernels is evaluated as a single fused
#' exponential, exp(-p*log(1+dt/c) - q*log(1+r2/d)), and all per-parent
#' constants are hoisted out of the inner pair loop. This is mathematically
#' identical to evaluating the two pow() factors separately (results agree
#' to floating-point rounding).
#'
#' @param t      Numeric vector of event times (sorted ascending, shifted
#'               so the window starts at 0).
#' @param x      Numeric vector of x-coordinates.
#' @param y      Numeric vector of y-coordinates.
#' @param mag    Numeric vector of event magnitudes.
#' @param W_val  Numeric vector of inhomogeneous background weights (set to
#'               1 for homogeneous, 0 for points in a zero-background region).
#' @param mu     Background rate (events per unit time over the full window).
#' @param A      Productivity scaling constant.
#' @param alpha_m  Magnitude efficiency parameter.
#' @param cc     Omori-Utsu temporal offset (\eqn{c > 0}).  Named \code{cc}
#'               to avoid collision with R's \code{c()} function.
#' @param p      Omori-Utsu temporal exponent (\eqn{p > 1}).
#' @param D      Spatial spread base parameter (\eqn{D > 0}).
#' @param gamma_par  Magnitude-dependent spatial scaling (\eqn{\gamma \ge 0}).
#' @param q      Spatial power-law exponent (\eqn{q > 1}).
#' @param m0     Reference (cutoff) magnitude.
#' @param areaS  Area of the spatial observation window \eqn{|S|}.
#' @param t_max  Length of the temporal observation window \eqn{T}.
#' @param t_trunc  Temporal truncation horizon.  Set to a negative value
#'                 (default \code{-1}) to disable truncation.
#' @return Scalar log-likelihood value.
etas_loglik_inhom_cpp <- function(t, x, y, mag, W_val, mu, A, alpha_m, cc, p, D, gamma_par, q, m0, areaS, t_max, t_trunc = -1.0) {
    .Call(`_PPDisentangle_etas_loglik_inhom_cpp`, t, x, y, mag, W_val, mu, A, alpha_m, cc, p, D, gamma_par, q, m0, areaS, t_max, t_trunc)
}

#' Conditional ETAS log-likelihood with observed parent history
#'
#' Evaluates the ETAS likelihood only for events in the post-treatment
#' observation window while allowing earlier events to contribute as parents.
#' The triggering compensator is integrated only over the observation window,
#' including the remaining offspring mass of pre-window parents.
#'
#' @param post_t,post_x,post_y Coordinates and times of observed events.
#' @param W_val Background weights for the observed events.
#' @param parent_t,parent_x,parent_y,parent_mag Coordinates, times, and
#'   magnitudes of all possible parents (history plus observed events), sorted
#'   by time.
#' @param t_start,t_end Bounds of the observation window.
#' @inheritParams etas_loglik_inhom_cpp
#' @return Scalar conditional log-likelihood value.
etas_loglik_inhom_filtration_cpp <- function(post_t, post_x, post_y, W_val, parent_t, parent_x, parent_y, parent_mag, mu, A, alpha_m, cc, p, D, gamma_par, q, m0, areaS, t_start, t_end, t_trunc = -1.0) {
    .Call(`_PPDisentangle_etas_loglik_inhom_filtration_cpp`, post_t, post_x, post_y, W_val, parent_t, parent_x, parent_y, parent_mag, mu, A, alpha_m, cc, p, D, gamma_par, q, m0, areaS, t_start, t_end, t_trunc)
}

#' Simulate ETAS offspring via BFS branching
#'
#' Starting from a set of parent events, generates all offspring (and their
#' descendants) using the ETAS triggering kernel with Omori-Utsu temporal
#' delays and isotropic power-law spatial displacements.
#'
#' **Temporal delays** are sampled by inverse-CDF from the Omori-Utsu
#' distribution:
#' \deqn{\Delta t = c\bigl[(1 - u)^{-1/(p-1)} - 1\bigr], \quad u \sim
#'   \mathrm{Uniform}(0, G_{\max})}
#' where \eqn{G_{\max} = 1} (no truncation) or
#' \eqn{G_{\max} = 1 - (1 + t_{\mathrm{trunc}}/c)^{-(p-1)}} (truncated).
#'
#' **Spatial displacements** are sampled by inverse-CDF from the isotropic
#' power-law kernel (magnitude-dependent spread):
#' \deqn{r^2 = d(m)\bigl[(1 - u)^{-1/(q-1)} - 1\bigr], \quad
#'   d(m) = D\exp\bigl(\gamma(m - m_0)\bigr)}
#' with direction uniform on \eqn{[0, 2\pi)}.
#'
#' **Offspring magnitudes** are drawn either from a Gutenberg-Richter
#' distribution \eqn{m = m_0 + \mathrm{Exp}(\beta_{GR})} (when
#' \code{beta_gr > 0}) or by resampling uniformly from the supplied
#' \code{mag_pool} vector.
#'
#' @param parent_x,parent_y,parent_t,parent_mag  Numeric vectors of parent
#'   coordinates and magnitudes.
#' @param A         Productivity scaling.
#' @param alpha_m   Magnitude efficiency.
#' @param cc        Omori-Utsu temporal offset (\eqn{c > 0}).
#' @param p         Omori-Utsu temporal exponent (\eqn{p > 1}).
#' @param D         Spatial spread base parameter.
#' @param gamma_par Magnitude-spatial scaling (\eqn{\gamma}).
#' @param q         Spatial power-law exponent (\eqn{q > 1}).
#' @param m0        Reference magnitude.
#' @param beta_gr   Gutenberg-Richter \eqn{\beta = b \ln 10}.  Set to 0 or
#'                  negative to use empirical resampling from \code{mag_pool}.
#' @param t_min,t_max  Temporal observation window.
#' @param x_min,x_max,y_min,y_max  Spatial bounding box.
#' @param t_trunc   Temporal truncation (negative to disable).
#' @param mag_pool  Numeric vector of observed magnitudes for resampling.
#'                  Ignored when \code{beta_gr > 0}.
#' @param max_generations Maximum offspring generations to simulate. Negative
#'   values retain the full branching process; one returns immediate children.
#' @return A \code{DataFrame} with columns \code{x}, \code{y}, \code{t},
#'   \code{mag} containing all offspring (excluding parents).
sim_etas_children_cpp <- function(parent_x, parent_y, parent_t, parent_mag, A, alpha_m, cc, p, D, gamma_par, q, m0, beta_gr, t_min, t_max, x_min, x_max, y_min, y_max, t_trunc = -1.0, mag_pool = as.numeric( c()), max_generations = -1L) {
    .Call(`_PPDisentangle_sim_etas_children_cpp`, parent_x, parent_y, parent_t, parent_mag, A, alpha_m, cc, p, D, gamma_par, q, m0, beta_gr, t_min, t_max, x_min, x_max, y_min, y_max, t_trunc, mag_pool, max_generations)
}

#' Batched Hawkes filtration log-likelihood over labellings
#'
#' @param t,x,y Shared event geometry, sorted ascending in time.
#' @param is_observed Integer 0/1 length-n: 1 = contributes a log-intensity
#'   term (post-treatment observation); 0 = parent-only (pre-history).
#' @param member Integer matrix n x K: 1 if event belongs to the process
#'   under that labelling (parents + observed members).
#' @param W_val Length-n background weights (used only for observed events).
#' @param mu,alpha,beta,K Hawkes parameters.
#' @param areaS Active spatial area.
#' @param t_start,t_end Observation window for the compensator.
#' @param adjust_factor Background compensator scale (usually 1).
#' @param t_trunc Temporal truncation (negative disables).
#' @param kernel_type 0 = exponential, 1 = power-law temporal.
#' @param cc,p Power-law temporal parameters.
#' @param spatial_kernel_type 0 = exponential, 1 = power-law spatial.
#' @param spatial_q,spatial_d Power-law spatial parameters.
#' @param n_threads Worker threads (1 = serial).
#' @return Length-K numeric vector of log-likelihoods.
#' @keywords internal
hawkes_loglik_inhom_filtration_batch_cpp <- function(t, x, y, is_observed, member, W_val, mu, alpha, beta, K, areaS, t_start, t_end, adjust_factor = 1.0, t_trunc = -1.0, kernel_type = 0L, cc = 1.0, p = 2.0, spatial_kernel_type = 0L, spatial_q = 2.0, spatial_d = -1.0, n_threads = 1L) {
    .Call(`_PPDisentangle_hawkes_loglik_inhom_filtration_batch_cpp`, t, x, y, is_observed, member, W_val, mu, alpha, beta, K, areaS, t_start, t_end, adjust_factor, t_trunc, kernel_type, cc, p, spatial_kernel_type, spatial_q, spatial_d, n_threads)
}

hawkes_loglik_inhom_cpp <- function(t, x, y, W_val, mu, alpha, beta, K, areaS, t_max, t_trunc = -1.0, kernel_type = 0L, cc = 1.0, p = 2.0, spatial_kernel_type = 0L, spatial_q = 2.0, spatial_d = -1.0) {
    .Call(`_PPDisentangle_hawkes_loglik_inhom_cpp`, t, x, y, W_val, mu, alpha, beta, K, areaS, t_max, t_trunc, kernel_type, cc, p, spatial_kernel_type, spatial_q, spatial_d)
}

hawkes_loglik_inhom_filtration_cpp <- function(post_t, post_x, post_y, W_val, parent_t, parent_x, parent_y, mu, alpha, beta, K, areaS, t_start, t_end, adjust_factor = 1.0, t_trunc = -1.0, kernel_type = 0L, cc = 1.0, p = 2.0, spatial_kernel_type = 0L, spatial_q = 2.0, spatial_d = -1.0) {
    .Call(`_PPDisentangle_hawkes_loglik_inhom_filtration_cpp`, post_t, post_x, post_y, W_val, parent_t, parent_x, parent_y, mu, alpha, beta, K, areaS, t_start, t_end, adjust_factor, t_trunc, kernel_type, cc, p, spatial_kernel_type, spatial_q, spatial_d)
}

sim_hawkes_children_cpp <- function(parent_x, parent_y, parent_t, alpha, beta, K, t_min, t_max, x_min, x_max, y_min, y_max, t_trunc = -1.0, kernel_type = 0L, cc = 1.0, p = 2.0, spatial_kernel_type = 0L, spatial_q = 2.0, spatial_d = -1.0) {
    .Call(`_PPDisentangle_sim_hawkes_children_cpp`, parent_x, parent_y, parent_t, alpha, beta, K, t_min, t_max, x_min, x_max, y_min, y_max, t_trunc, kernel_type, cc, p, spatial_kernel_type, spatial_q, spatial_d)
}

tile_index_rect_cpp <- function(x, y, xgrid, ygrid) {
    .Call(`_PPDisentangle_tile_index_rect_cpp`, x, y, xgrid, ygrid)
}

