# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hawkes_loglik_inhom_cpp <- function(t, x, y, W_val, mu, alpha, beta, K, areaS, t_max) {
    .Call(`_PPDisentangle_hawkes_loglik_inhom_cpp`, t, x, y, W_val, mu, alpha, beta, K, areaS, t_max)
}

sim_hawkes_children_cpp <- function(parent_x, parent_y, parent_t, alpha, beta, K, t_min, t_max, x_min, x_max, y_min, y_max) {
    .Call(`_PPDisentangle_sim_hawkes_children_cpp`, parent_x, parent_y, parent_t, alpha, beta, K, t_min, t_max, x_min, x_max, y_min, y_max)
}

